Update build-pyinstaller.yml

diff --git a/.github/workflows/build-pyinstaller.yml b/.github/workflows/build-pyinstaller.yml
--- a/.github/workflows/build-pyinstaller.yml
+++ b/.github/workflows/build-pyinstaller.yml
@@ -18,7 +18,30 @@ jobs:
           python_ver: '3.8'
           spec: 'reshapeGUI.spec'
           requirements: 'requirements.txt'
+          upload_exe_with_name: 'ReshaperGUI'
           options: --onefile, --name "ReshaperGUI", --windowed
+
+      - name: Check PyInstaller success
+        run: |
+          if [ "${{ steps.pyinstaller.outcome }}" != "success" ]; then
+            echo "PyInstaller failed to create the executable."
+            exit 1
+          fi
+        shell: bash
+
+      - name: List dist directory contents
+        run: dir dist
+        shell: bash
+
+      - name: Find executable file
+        run: |
+          exe_file=$(find dist -iname "reshapergui.exe" -type f)
+          if [ -z "$exe_file" ]; then
+            echo "Executable file not found in dist directory."
+            exit 1
+          fi
+          echo "EXE_FILE=$exe_file" >> $GITHUB_ENV
+        shell: bash
 
       - name: Extract version from Python file
         run: |
@@ -56,7 +79,7 @@ jobs:
 
       - name: Rename executable
         run: |
-          mv dist/ReshaperGUI.exe dist/ReshaperGUI-${{ env.new_tag }}.exe
+          mv "${{ env.EXE_FILE }}" "dist/reshapeGUI-${{ env.new_tag }}.exe"
         shell: bash
 
       - name: Upload Executable to GitHub Release
